# Generated by Django 4.1.1 on 2022-09-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=2)),
                ('sobrenome', models.CharField(max_length=2)),
                ('idade', models.CharField(max_length=2)),
                ('nascimento', models.DateField()),
                ('descricao', models.TextField(max_length=200)),
            ],
        ),
    ]
