# Generated by Django 4.1.1 on 2022-09-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='nome',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='sobrenome',
            field=models.CharField(max_length=16),
        ),
    ]
